### ISSUE TITLE
Support custom arguments to be specified directly on configuration file.

### ISSUE THREAD

**Issue by juan131** [bitnami/bitnami-docker-redis#117]
As discussed at https://github.com/helm/charts/pull/7745, it'd be nice to allow uses to specify **redis-server** args directly to the configuration file instead of adding it via env. variables such as **REDIS_EXTRA_FLAGS**

**Comment by jlegrone** [comment]
@juan131 custom conf files can be provided for inclusion with a flag, so your second approach already handles the custom config file use case as well.

Example:
https://github.com/helm/charts/blob/198a7f72cf7d1abe6ef84edace48696888dc0479/stable/redis/templates/redis-master-statefulset.yaml#L82-L85

**Comment by jlegrone** [comment]
Looking at `run.sh` now, I think the good news is that it's not a breaking change to support this because it looks like args to the entrypoint are currently completely ignored.

https://github.com/bitnami/bitnami-docker-redis/blob/7a9ec56a0e981bbf526254decb044e229bbe6e2a/4.0/ol-7/rootfs/run.sh#L15-L21

`REDIS_EXTRA_FLAGS` can continue to be used (maybe with a deprecation warning), and any arguments to the entrypoint can be passed along to `redis-server` transparently.

**Comment by juan131** [comment]
Hi @jlegrone 

I think I can see you point, do you mean sth like:

```
ARGS="$REDIS_BASEDIR/etc/redis.conf --daemonize no" $@"

REDIS_EXTRA_FLAGS=${REDIS_EXTRA_FLAGS:-} 
  
 # configure extra command line flags 
 if [[ -n "$REDIS_EXTRA_FLAGS" ]]; then
     warn "REDIS_EXTRA_FLAGS is depredated. Please use XXX instead"
     ARGS+=" $REDIS_EXTRA_FLAGS" 
 fi
```

**Comment by jlegrone** [comment]
@juan131 yes, exactly. I'd be happy to review if you tag me on a PR.

**Comment by juan131** [comment]
Yes sure!!

**Comment by juan131** [comment]
@jlegrone I just created the PR. Please feel free to review it.

**Comment by juan131** [comment]
Hi @jlegrone I just landed the changes and trigger the release the job. I'll update the issue as soon as a new Redis image is released.

**Comment by juan131** [comment]
Hi @jlegrone the new image including the changes that allow you to send the `redis-server` arguments directly to the entrypoint has been released. Please feel free to use it (**bitnami/redis:4.0.11-r50** and provide us feedback about it.
