### ISSUE TITLE
How should I expose ports for (master-slave mode)

### ISSUE THREAD

**Issue by shenjiayu** [bitnami/bitnami-docker-redis#167]
Should I only expose 6379:6379 of the master node to other containers. What should I do with the slave node then? Would the master node auto direct traffic thru to other slave nodes or I have to explicitly expose all redis nodes and connect to them according to the requirements such as the master node（6379:6379） only for writing and slave nodes（6380:6379） for reading.

**Comment by marcosbc** [comment]
@shenjiayu We have a Docker Compose file example showing you how to configure replication with Redis. See: https://github.com/bitnami/bitnami-docker-redis/blob/master/docker-compose-replicaset.yml

If you wish to use a Redis multi-master clustering topology, you can check out the [Bitnami Redis Cluster Docker image](https://github.com/bitnami/bitnami-docker-redis-cluster).

**Comment by shenjiayu** [comment]
@marcosbc Thanks for your reply..But I couldn't find any clues how I should expose my ports.

**Comment by marcosbc** [comment]
@shenjiayu Note that if both containers are running inside the [Docker Network](https://docs.docker.com/network/) you will not need to expose the ports in `docker-compose.yml`. That is because inside a Docker Network, all containers can access each other's ports (as long as they share the same Docker Network).

Therefore, as long as you use Docker Compose, you should not worry about exposing the ports to your computer as each container already can communicate between them.

**Comment by shenjiayu** [comment]
@marcosbc Thanks for your explanation again, very helpful.
