### ISSUE TITLE
redis-cli --csv BGSAVE/LASTSAVE do not return ERROR Message ( out of disk ) 

### ISSUE THREAD

**Issue by AhmedMItman** [bitnami/bitnami-docker-redis#169]
I was trying to take database dump using:
```
redis-cli --csv BGSAVE
CURR_DATE=$(date +%s)
while true; do
	# LASTSAVE returns epoch of last successfull background dump process
	LAST_SAVE=$(redis-cli  --csv LASTSAVE)
	[ "$LAST_SAVE" -ge "$CURR_DATE" ] && break || sleep 30
done
```
It did not exit from `While loop`, because LAST_SAVE did not change and it tried to save data into disk,but it failed

**Reason:**
 Their was not an available Storage space, and Redis was trying to put new dump data.

**Suggestion:**
Their should be a `time out` with error message `Server out of disk`, and program should exit with error code

**Comment by joancafom** [comment]
Hello @AhmedMItman and thanks for your comment!

I was successfully able to reproduce your issue. In fact, I used a read-only directory to dump the data and still it happens the same. According to the official [documentation](https://redis.io/commands/lastsave), the `LASTSAVE` property should return the UNIX TIME of the last DB save executed with **success**, so this is definitely an issue. However, this issue is related with the application itself and there is nothing we can do to fix that behaviour.

In order to make this change you could try opening an issue in the [Redis repository](https://github.com/antirez/redis) and let them know there. Thanks!
