### ISSUE TITLE
[feature request] Add env or something to get machine ip from dns not hosts file

### ISSUE THREAD

**Issue by tartemov** [bitnami/bitnami-docker-redis#174]
If you are using redis with HA-configuration with redis-sentinel in docker-compose/docker swarm, there is some issue - https://stackoverflow.com/questions/58706332/sentinel-cannot-promote-initial-master-back-to-master-mode-after-failover/62389682#62389682

It happens cause sentinel get IP address for redis-master service, but redis-master announce different IP (redis-master container IP).

So when sentinel try to change role for old master - it send REPLICAOF command instead setting master role.

**Describe the results you received:**

Sentinel breaks redis-cluster in this case.

**Describe the results you expected:**

This my fork - https://github.com/tartemov/bitnami-docker-redis
I change only one function dns_lookup - to get IP from DNS records:
`dns_lookup() {
    local host="${1:?host is missing}"
    getent -s hosts:dns ahosts "$host" | awk '/STREAM/ {print $1 }'
}`

Here it is docker-compose configuration:
`
services:
  redis-master:
    image: <docker-registry>/redis:5.0.9
    hostname: "redis-master"
    environment:
      REDIS_REPLICATION_MODE: master
      ALLOW_EMPTY_PASSWORD: 'yes'
      REDIS_AOF_ENABLED: 'no'
  redis-slave-1:
    image: <docker-registry>/redis:5.0.9
    environment:
      REDIS_REPLICATION_MODE: slave
      REDIS_MASTER_HOST: redis-master
      ALLOW_EMPTY_PASSWORD: 'yes'
      REDIS_AOF_ENABLED: 'no'
  redis-slave-2:
    image: <docker-registry>/redis:5.0.9
    environment:
      REDIS_REPLICATION_MODE: slave
      REDIS_MASTER_HOST: redis-master
      ALLOW_EMPTY_PASSWORD: 'yes'
      REDIS_AOF_ENABLED: 'no'
  sentinel:
    image: bitnami/redis-sentinel:5.0.9-debian-10-r49
    environment:
      REDIS_MASTER_HOST: redis-master
      ALLOW_EMPTY_PASSWORD: 'yes'
      REDIS_AOF_ENABLED: 'no'
      REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS: 5000
      REDIS_SENTINEL_FAILOVER_TIMEOUT: 60000
    deploy:
      mode: replicated
      replicas: 3
`

With setting hostname - dns_lookup can find redis-master in docker dns records and set IP correctly

It will really helps if you can provide mechanism to get IP for redis from different source (DNS, hosts)

**Comment by joancafom** [comment]
Hi @tartemov ,

Thanks for opening the issue. I am trying to bound the problem as to understand it better and there are some questions that come to my mind. Does this happens exclusively in Docker Swarm mode due to the Service topology ? 

We have a redis chart solution, using Services in front of pods. I am trying to extrapolate to that scenario, which I think is similar, and apparently we do not perform any changes for it to work.

On the one hand, I could try to implement one env variables that allows the user to choose whether to resolve IP from DNS or host. I think, that together with your proposed changes, that would be an option. What do you think?

Any other further comments are appreciated, thanks!

**Comment by tartemov** [comment]
>> Does this happens exclusively in Docker Swarm mode due to the Service topology?

**Comment by joancafom** [comment]
Hi @tartemov 

I have been reviewing the attached conversation, and to my understanding (correct my if I am wrong) it all seems to be caused by a bug on how Docker Swarm handles hostnames and different IPs. Hence, it should be a matter of time from their side to fix it.

Regarding the possible options on the meanwhile I do like your point of view on providing a custom script to define hostname/announce ip. That will provide much more flexibility for the end user and will let the rest of the code as it is, ensuring that no other scenarios are broken. 

Am I right on my understanding? If so, I would work on a way to provide a custom init script that will let the user define the announced ip 😃

Thanks very much!

**Comment by tartemov** [comment]
Hi @joancafom!
Yes, you are quite right! And custom script will be really more flexible solution, thanks!

**Comment by joancafom** [comment]
Hi @tartemov ,

I have been working on this in order to workaround the issue and am planning to add it to `README.md` just so other users know as well!

1. We are going to modify the provided `setup.sh`. Copy the current one in order to use it as a base:

```console
$ cp ./6.0/debian-10/rootfs/opt/bitnami/scripts/redis/setup.sh ./customSetup.sh
```

2. Append the following code at the end of `customSetup.sh` file:

```bash
# CHANGE THE ANNOUNCED IP
if [[ -n "$REDIS_REPLICATION_MODE" ]]; then
    ANNOUNCED_IP=$(getent -s hosts:dns ahosts $(hostname) | awk '/STREAM/ {print $1 }')
    redis_conf_set replica-announce-ip "${ANNOUNCED_IP}"
fi
```

3. Modify your `docker-compose.yaml` in order to overwrite the standard `setup.sh` in your master node:

```yaml
...
  redis-primary:
...
    volumes:
      - 'redis_data:/bitnami/redis/data'
      - './customSetup.sh:/opt/bitnami/scripts/redis/setup.sh'
...
```

You can now run the container and adapt the way the IP is set up in the configuration file!

Could this help? Thanks!

**Comment by tartemov** [comment]
Hi! I've checked configuration and it works.
But in Docker Swarm with multiple nodes I can't use volumes like you did, so I've used configs:
`
version: '3.7'

configs:
  setup:
    file: ./customSetup.sh

services:
  redis-master:
    image: bitnami/redis:5.0.9-debian-10-r61
    hostname: "redis-master"
    environment:
      REDIS_REPLICATION_MODE: master
      ALLOW_EMPTY_PASSWORD: 'yes'
      REDIS_AOF_ENABLED: 'no'
    configs:
      - source: setup
        target: /opt/bitnami/scripts/redis/setup.sh
        uid: "1001"
        mode: 0755
`

This solution works as expected.

**Comment by joancafom** [comment]
Hooray, thanks so much for testing it out and sharing your solution with the community!!
