### ISSUE TITLE
IPV6 bind [::]

### ISSUE THREAD

**Issue by diwu1989** [bitnami/bitnami-docker-redis#199]
**Description**

The redis server only binds to 0.0.0.0, but not ipv6 [::]
Please add support to bind to ipv6 wildcard as well so that it is possible to expose redis via ipv6.

**Steps to reproduce the issue:**

1. Enable ipv6 on docker daemon
2. Run bitnami redis with default flags
3. Verify whether redis is reachable via ipv6

**Describe the results you received:**

Redis server only binds to ipv4
**Describe the results you expected:**
Expect the redis server to bind to ipv6 address as well as ipv4

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
ubuntu@sf-db1:~$ docker version
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:13 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:25 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
ubuntu@sf-db1:~$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 7
 Server Version: 20.10.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-66-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 125.9GiB
 Name: sf-db1
 ID: H6LS:4CMJ:TPFH:TYE3:MAXP:O6U2:6MGY:BAI4:FNFZ:YQR5:57RL:BSTO
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No blkio weight support
WARNING: No blkio weight_device support
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
```
CONTAINER ID   IMAGE                             COMMAND                  CREATED         STATUS        PORTS                                                                     NAMES
9557794f671c   bitnami/redis:latest              "/opt/bitnami/script…"   2 seconds ago   Up 1 second   0.0.0.0:6379->6379/tcp, :::6379->6379/tcp                                 redis
```
I can port map ipv6, but redis server process internally only listen on 0.0.0.0, but not :::

**Comment by migruiz4** [comment]
Hi @diwu1989 ,

I think it may be because the container binds `0.0.0.0`

https://github.com/bitnami/bitnami-docker-redis/blob/663851ff60798cc00ad69346cffda328259068a6/6.2/debian-10/rootfs/opt/bitnami/scripts/libredis.sh#L375

I have tried modifying it to `redis_conf_set bind "0.0.0.0 ::"` and seems it would resolve the issue:

```
> docker run --rm -it --network="redis-net" --entrypoint bash redis-ipv6 
I have no name!@f093262b6037:/$ redis-cli -h 2001:db8::2
[2001:db8::2]:6379> 
```

I have created a new image modifying the above line named `redis-ipv6`, enabled ipv6 in docker, and created the IPv6 network `redis-net`.

And as you can see the result was successful.

For reference, same scenario didn't work with the latest release:
```
> docker run --rm -it --network="redis-net" --entrypoint bash docker.io/bitnami/redis:6.2-debian-10
I have no name!@dce80ebfd2d4:/$ redis-cli -h 2001:db8::2
Could not connect to Redis at 2001:db8::2:6379: Connection refused
```

NOTE: Although I only shared the client-side, the server is also running the image with and without the fix.

**Comment by migruiz4** [comment]
A new image including this fix will be released soon, I will let you know as soon as it is available.

**Comment by migruiz4** [comment]
Hi @diwu1989,

I'm sorry for the late response, I forgot to share here that the new images released since March 6th included a fix that allows connecting using IPv6.

https://github.com/bitnami/bitnami-docker-redis/blame/master/5.0/debian-10/rootfs/opt/bitnami/scripts/libredis.sh#L372

Thank you for reporting this and helping us improve!

I will proceed to close this issue, if you have any further questions let me know.
