### ISSUE TITLE
Missing chart versions older than 15.7.0

### ISSUE THREAD

**Issue by ir33k** [bitnami/bitnami-docker-redis#247]
### Name and Version

bitnami/redis 10.9.0

### What steps will reproduce the bug?

```sh
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm repo update
$ helm search repo bitnami/redis --versions	# Oldest chart version is 15.7.0
$ helm install my-redis bitnami/redis --version 10.9.0
Error: INSTALLATION FAILED: failed to download "bitnami/redis" at version "10.9.0"
```

### What is the expected behavior?

Chart versions older than 15.7.0 should be available.

### What do you see instead?

Only versions from chart 15.7.0 to 16.11.2 are available.

### Additional information

Recently old script failed to install mentioned version. I thought that support for older versions was dropped for some reason but found no information. Any idea why older versions are not available?

**Comment by carrodher** [comment]
It is due to a recent change in the retention policy, the Helm charts were not deleted but the `index.yaml` was updated to keep Helm charts from the latest 6 months.

Please, take a look a this pinned issue https://github.com/bitnami/charts/issues/10539 to have more info about this change and some ways to use previous versions as usual by adding a previous `index.yaml` version to the `helm` client.

The `index.yaml` is stored in this repository under the [_index_ branch](https://github.com/bitnami/charts/tree/index/bitnami), users should be able to use any commit in that branch to add a previous version of the `index.yaml`.

- Manually using `helm repo add`
```console
$ helm repo add bitnami-pre-2022 https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
"bitnami-pre-2022" has been added to your repositories
```
- When used as a dependency in _Chart.yaml_:
```diff
  - name: postgresql
    version: 8.1.0
-   repository: https://charts.bitnami.com/bitnami
+   repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
    condition: postgresql.enabled
```

In order to consolidate the conversations and unify the effort, we will answer questions as well as any other communication in the above mentioned GH issue, closing the other ones.
