### ISSUE TITLE
Make image more lightweight

### ISSUE THREAD

**Issue by schickling** [bitnami/bitnami-docker-redis#7]
First of all for this great image. It's a lot more useful and convenient than the official docker one. Good job!

One suggestion though: Alpine is getting more and more popular as a super small base image and would be a good choice in order to drastically reduce the footprint of this docker image.

What do you think?

**Comment by prydonius** [comment]
Hey @schickling, thank you for the feedback :). We have considered Alpine as a base image in the past (https://github.com/bitnami/bitnami-docker-base/tree/master/alpine), but ran into some issues with our installers requiring glibc rather than musl.

We decided to go with a base image that people would be more familiar with for now (especially for language runtimes where people are more likely to use apt-get). However, we definitely would like to support multiple base images (e.g. RHEL based, Alpine) in the future and allow users to select their preferred base, do you think this could be useful?

**Comment by schickling** [comment]
Of course! But keep in mind that the redis image is unlikely to be extended or used as a base image.

**Comment by prydonius** [comment]
It's true that most people won't build on top of the redis image. However, our goal is to focus on maintaining a common base across all our images. Using Bitnami images for your whole stack allows you to efficiently make use of layers (e.g. https://imagelayers.io/?images=bitnami%2Fredis,bitnami%2Fruby,bitnami%2Fnginx).  It also allows you to have a consistent user experience across all of our images.

**Comment by oryband** [comment]
@prydonius yes! please create an `:x.x.x-alpine` image, would be most useful.

**Comment by sameersbn** [comment]
@schickling @oryband We would like to bring to your attention the [bitnami/minideb](https://hub.docker.com/r/bitnami/minideb/) image that is now used as the base image in all Bitnami Container Offerings. minideb is a glibc based, light weight and stripped down version of debian which includes `apt` for installing packages from the debian repositories. Thanks to `bitnami/minideb`, the `bitnami/redis`, and other Bitnami Images, are now far more lightweight. 

For more information on minideb please read out our engineering blog post titled [Minideb: A New Container Base Image](https://engineering.bitnami.com/2016/11/02/minideb-a-new-container-base-image.html). 

Let us know your comments and feedback. We would like to hear back from you.
