### ISSUE TITLE
Turn slave into master

### ISSUE THREAD

**Issue by phlegx** [bitnami/bitnami-docker-redis#83]
Once started as a slave (via docker-compose), can a container be started as a master?

I mean I have two docker-compose file, one is running a master and the other the slave. Now when the master is down, can I just stop the slave on the other machine and start it as a master with the same volume?

If this is not possible, what is the plan to turn a slave into a master with this image in case the master fails?

thanks

**Comment by javsalgar** [comment]
Hi, 

Thanks for the suggestion. That's something we are looking into, but not for the short term.

**Comment by phlegx** [comment]
Hi @javsalgar!

Thanks for the info! 

I was thinking about this a bit again. Could a switch workk when we would do the volume stuff differently, namely not include the volume like this, so (as it currently is) the config is included as well:

```
docker run -v /path/to/redis-persistence:/bitnami/redis bitnami/redis:latest
```
but instead like like this:

```
docker run -v /path/to/redis-persistence/redis/data:/bitnami/redis/data bitnami/redis:latest
```

So basically the config directory would completely stay inside the container.

**Comment by prydonius** [comment]
@phlegx right now I don't believe this is possible because we define the `VOLUME` in the Dockerfile, so Docker will always mount a volume even if you don't specify one. We've discussed removing the `VOLUME` declarations and will work on doing so (see https://github.com/bitnami/bitnami-docker-wordpress/issues/96), and after this you should be able to only persist the data dir and keep the config dir in the container.
